name: bill_planner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  chips_choice: ^3.0.1
  cupertino_icons: ^1.0.6
  easy_date_timeline: ^1.1.3
  enhance_stepper: ^1.0.1
  equatable: ^2.0.5
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.4
  persistent_bottom_nav_bar: ^6.2.1
  timeline_tile: ^2.0.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
